apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  selector:
    app: nextjs
  ports:
    - protocol: TCP
      port: 3000   # The exposed port on the VM
      targetPort: 3000
      nodePort: 30007  # Any port in the range 30000-32767
  type: NodePort
